defaults:
    - transformer_defaults
    - engine: regression
    - _self_
engine:
  target_key:
    - positions
    - directions
  target_scale_factor:
    positions: 1
    directions: 0.01
model:
  num_output_channels: 6
hydra:
  run:
    dir: /ml_workshop/watchmal_tutorial/regression_run/
