defaults:
    - data: tutorial_data
    - model: resnet18
    - tasks/train: train_resnet
    - tasks/restore_best_state: restore_best_state
    - tasks/evaluate: test
tasks:
  train:
    epochs: 3
    val_interval: 5
    num_val_batches: 2
    data_loaders:
      validation:
        batch_size: 1024
gpu_list: [] # train on CPU
seed: null
dump_path: './outputs/'
hydra:
  job:
    chdir: True
