gpu_list:
    - 1

seed: null
dump_path: './outputs/'
defaults:
    - data: iwcd_segmentation
    - data/dataset: iwcd_segmentation
    - model: unet3d
    - engine: segmentation
    - tasks/train: train_unet3d
    - optimizers@tasks.train.optimizers: adam
    - sampler@tasks.train.data_loaders.train.sampler: subset_random
    - sampler@tasks.train.data_loaders.validation.sampler: subset_random
    - tasks/restore_best_state: restore_best_state
    - tasks/evaluate: test
    - sampler@tasks.evaluate.data_loaders.test.sampler: subset_sequential
