defaults:
    - wcte_defaults
    - engine: regression
    - override loss@tasks.train.loss: huber
    - override loss@tasks.evaluate.loss: huber
    - _self_
engine:
  target_key:
    - positions
    - directions
  target_scale_factor:
    positions: 1
    directions: 0.01
model:
  num_output_channels: 6
